### ISSUE TITLE
Need some information Regarding ToolFlag Status

### ISSUE THREAD

**Issue by arbazkiraak** [g0dA/burpsuite_extender#1]
What does this  4 and 64 stand's for ?  i tried looking for Burp Suite Doc's , Didn't found about toolflag code https://portswigger.net/burp/extender/api/burp/IHttpListener.html

if toolFlag == 4 or toolFlag == 64:

Let me know where i can know more about toolFlag's 

Thanks!

**Comment by g0dA** [comment]
The Doc is [here](https://portswigger.net/burp/extender/api/constant-values.html#burp.IBurpExtenderCallbacks)

you can see 

TOOL_PROXY  =  4
TOOL_REPEATER = 64 

"if toolFlag == 4 or toolFlag == 64:" means that we listen on proxy and repeater module

**Comment by arbazkiraak** [comment]
Thanks for it !
